name = "openilink-chatroom"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "openilink-chatroom"
database_id = "5981ca14-273e-4b7e-8071-b5ca72bb3168"

[vars]
WORKER_URL = "https://openilink-chatroom.cinwell.workers.dev"
